package tn.esprit.students.Models;

public enum Localisation {

	ARIANA,BEJA,SOUSSE,BIZERTE,GABES,NABEUL,JEMDOUBA,KAIROUAN,ZAGHOUAN,KEBILI,KEF,MAHDIA,MANNOUBA,MEDENIN,MONASTIR,GAFSA,SFAX,SIDIBOUZID,SILIANA,BENAROUS,TATAOUINE,TOZEUR,TUNIS,KASSERINE

}
